### PR TITLE
feat: handle complex types

### LINKED ISSUE #208: [oas2ts] Handle complex types
As reported by @toomuchdesign, the underlying library we're using, `json-schema-to-typescript`, has troubles with complex types which are not compiled with the same quality as, e.g. https://github.com/drwpow/openapi-typescript.

As an example it's splitting types across files whereas the latter keeps them in the same one. We should consider improving this, even switching the underlying library to a different one.

### PR DESCRIPTION
**Pull request by faizplus**
## Features
 - Generates types in a single file instead of splitting types across files

## Limitations
Currently, generated file name is hardcoded as `types.ts` or `types.d.ts` which gets generated into the provided output folder. We can create a new option for filename or update the output folder to output file.

Closes #208

## Other Options
Also explored other packages like https://github.com/drwpow/openapi-typescript instead of `json-schema-to-typescript`. This generates types for entire file in the following format which is not ideal for developers. For example, to access `Order` type, we have to use `components["schemas"]["Order"]`

### Sample file generated by `openapi-typescript` 

```javascript
export interface components {
  schemas: {
    Order: {
      /**
       * Format: int64
       * @example 10
       */
      id?: number;
      /**
       * Format: int64
       * @example 198772
       */
      petId?: number;
      /**
       * Format: int32
       * @example 7
       */
      quantity?: number;
      /** Format: date-time */
      shipDate?: string;
      /**
       * @description Order Status
       * @example approved
       * @enum {string}
       */
      status?: "placed" | "approved" | "delivered";
      complete?: boolean;
    };
    ...
  };
  responses: never;
  parameters: never;
  requestBodies: {
    /** @description Pet object that needs to be added to the store */
    Pet?: {
      content: {
        "application/json": components["schemas"]["Pet"];
        "application/xml": components["schemas"]["Pet"];
      };
    };
    /** @description List of user object */
    UserArray?: {
      content: {
        "application/json": components["schemas"]["User"][];
      };
    };
  };
  headers: never;
  pathItems: never;
}


export interface paths {
  "/pet": {
    /**
     * Update an existing pet
     * @description Update an existing pet by Id
     */
    put: operations["updatePet"];
    /**
     * Add a new pet to the store
     * @description Add a new pet to the store
     */
    post: operations["addPet"];
  };
  ...
}

export type webhooks = Record<string, never>;

...
```

### CODE REVIEW

**Review by ilteoood — CHANGES_REQUESTED** [review]
To be honest, I'm -1 on this, for 2 reasons:

1) It introduces a breaking change. If everything is stored inside a single file, people needs to change all their imports to accomodate this change.

2) Putting everything in a single file is an anti-pattern. In complex projects, where we may have 100+ different types, putting everything in a single file will slow down both tsc and the suggestion provided by the IDE, which gives up if the file reaches a certain size.

If we still want to proceed with this (@simoneb I think you are the best on choosing this), may I ask you to rebase this work with #216? I would like to avoid conflicts

**Comment by simoneb** [comment]
@ilteoood I'll take your lead on this as I have no strong opinions. How would you suggest we handle this issue, any ideas?

**Comment by ilteoood** [comment]
> @ilteoood I'll take your lead on this as I have no strong opinions. How would you suggest we handle this issue, any ideas?

As a starting point, it would be great if @toomuchdesign could provide a repro of the issue he has just to understand what's the next point. WDYT?

**Comment by ilteoood** [comment]
Totally agree with you about that, we miss that feature either

**Pull request closed without merging**
